function Q = slip2latForce(alpha, load, car)
% SLIP2LATFORCE Computes tire lateral force due to slip angle.
%
%   Q = SLIP2LATFORCE(ALPHA, LOAD, CAR) calculates the lateral
%   force generated by a toroidal tire when subjected to a slip
%   angle ALPHA under a given vertical LOAD. Performs calculations
%   using a generalized Brush Tire Model.
%
%   Inputs:
%     ALPHA - Slip angle in radians.
%     LOAD  - Vertical load applied to the tire in Newtons.
%     CAR   - Object containing car properties.
%
%   Output:
%     Q - Lateral force in Newtons, negative for negative ALPHA.
%
%   Example:
%     car.TirePressure = 0.5;   % N/mm²
%     car.WheelRadius = 250;    % mm
%     car.WheelCurvature = 50;  % mm
%     car.WheelStiffness = 100; % N/mm
%     load = 1000;              % N
%     alpha = deg2rad(5);
%     Q = slip2latForce(alpha, load, car);
%
% See also CLASSDEF, PROPERTIES, DEG2RAD.

% THIS FUNCTION STILL NEEDS TO CONSIDER THRESHOLD SLIP (THIS IS UNIMPORTANT FOR SMALL ALPHA)

pressure =  car.TirePressure;   % assume no change in pressure under load [N/mm²]
contactPatch = load/pressure;   % [mm²]
R = car.WheelRadius;            % outer [mm]
r = car.WheelCurvature;         % tube [mm]

% Cartesian torus eqn (torus in x-z plane)
torusY = @(x,z) real(sqrt(r.^2 - (sqrt(x.^2+z.^2)-(R-r)).^2));
% this returns 0 for any (x,z) not on torus

% Find slice where load and P*A balance
sliceArea = 0; deformation = 0; inc = 1;
while true
    if sliceArea > contactPatch
        if inc <= 10^-9     % exit condition
            break;
        end
        deformation = deformation - inc;
        inc = inc/10;
    end
    deformation = deformation + inc;
    if deformation > r
        error("The tire won't hold the car up at this pressure.")
    end

    deformationPos = -R + deformation;

    % Contact patch
    semiMajorAxis = sqrt(R^2 - (R - deformation)^2);
    %semiMinorAxis = sqrt(r^2 - (r - deformation)^2);
    sliceArea = integral(@(x) 2*torusY(x, deformationPos), -semiMajorAxis, semiMajorAxis);
end

% RUNTIME COULD BE IMPROVED BY USING fzero() INSTEAD OF ITERATION

a = semiMajorAxis;
bFun = @(x) torusY(x, deformationPos);
K = car.WheelStiffness; % tire stiffness N/mm^2
A = contactPatch;

Q = 2*K/A * tan(alpha) * integral(@(x) (2*a-x).*bFun(x), 0, 2*a);
end
